/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  frameworksSidebar: [
    {
      type: 'category',
      label: 'Frameworks',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Compassionate Agility',
          items: [
            { type: 'autogenerated', dirName: 'frameworks/compassionate-agility' },
          ],
        },
        {
          type: 'category',
          label: 'Liberation Mapping',
          items: [
            { type: 'autogenerated', dirName: 'frameworks/liberation-mapping' },
          ],
        },
        {
          type: 'category',
          label: "Steward's Manual",
          items: [
            { type: 'autogenerated', dirName: 'frameworks/stewards-manual' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      items: [{ type: 'autogenerated', dirName: 'tools' }],
    },
    {
      type: 'category',
      label: 'Workshops',
      items: [{ type: 'autogenerated', dirName: 'workshops' }],
    },
    {
      type: 'category',
      label: 'Project',
      items: [{ type: 'autogenerated', dirName: 'project' }],
    },
    {
      type: 'category',
      label: 'Practitioner E2E Walkthrough',
      collapsed: false,
      items: [
        'practitioner-e2e/overview',
        'practitioner-e2e/path-a-new-organization-client',
        'practitioner-e2e/path-a-checkpoint',
        'practitioner-e2e/path-b-individual-coaching',
        'practitioner-e2e/path-b-checkpoint',
        'practitioner-e2e/path-c-continue-engagement',
        'practitioner-e2e/path-c-checkpoint',
        'practitioner-e2e/path-d-closure-variations',
        'practitioner-e2e/path-d-checkpoint',
        'practitioner-e2e/caveats',
      ],
    },
  ],
};

export default sidebars;
