import { isCoachingEngagement } from "../../tenant-config/src/index.ts";

export function buildClientPortalSidebarItems(config) {
  const items = [{ type: "doc", id: "intro", label: "Overview" }];

  for (const phase of config.phases) {
    items.push({
      type: "category",
      label: `${phase.id}. ${phase.label}`,
      items: [{ type: "autogenerated", dirName: `${phase.id}-${phase.slug}` }],
      link: { type: "generated-index" },
      collapsed: true,
    });
  }

  if (isCoachingEngagement(config.engagementType)) {
    items.push({
      type: "category",
      label: "Cohort",
      items: [{ type: "autogenerated", dirName: "cohort" }],
      link: { type: "generated-index" },
      collapsed: false,
    });
  }

  items.push({
    type: "category",
    label: "Tools & Assessments",
    items: [{ type: "autogenerated", dirName: "tools-assessments" }],
    link: { type: "generated-index" },
    collapsed: true,
  });

  return items;
}
